### ISSUE TITLE
Retained the Base-called information in SLOW5

### ISSUE THREAD

**Issue by loganylchen** [hasindu2008/slow5lib#61]
Hi there,

The SLOW5 really helped me a lot. May I ask if the base-called data, move_table, base_possibilities, etc. could also be converted to SLOW5 format? In my opinion, some of the down-stream analysing tools are still based on the base-called information as well as the raw signal information. 

Look forward to you reply,
Logan

**Comment by hasindu2008** [comment]
Hi,

I think this is what we discussed on the Twitter thread right? For sake of completeness, I will write the summary here.

SLOW5 spec supports auxiliary fields, so any custom information like this can be optionally saved if deemed required by the user. However, in the design of slow5tools we dropped the Analysis group mainly because:
1. SLOW5 is for storing raw signal data rather than intermediate data
2. That analyses content is software dependent and is not really raw data
3. Fastq and sequencing summary produced by Guppy contains the basecalled reads - so that data is redundant

ONT from very recently guppy does not seem to store those data in the FAST5 anyway. See https://community.nanoporetech.com/posts/proposed-changes-to-the-fa

Following are some suggestions on getting the move table using SLOW5:


If you really need ONT's move table you need to have guppy_basecall_server already running and use the following method:
MTD1:
1. Use [pyslow5](https://hasindu2008.github.io/slow5lib/pyslow5_api/pyslow5.html) to iterate through SLOW5 file
2. Send it through [ONT's pyguppy client](https://github.com/nanoporetech/pyguppyclient)  to get the move table 

If you can rely on the "move table" like structure computed in Nanopolish/f5c:
MTD2:
1. Use pyslow5 to iterate through SLOW5 file
2. Send it along with basecalled read through our [libabea](https://github.com/hasindu2008/libabea) to get the signal to basecalled read alignment

If you want a command-line tool for generating the "move table" like structure computed in Nanopolish/f5c:
MTD3:
Use this experimental module in f5c called f5c resquiggle available at https://github.com/hasindu2008/f5c/tree/resquiggle

In the long-term, I would suggest going along non-guppy approach as ONT's Guppy is not open source and they could simply ditch the move table function any time.  In fact ONT is moving towards a new basecaller called "Dorado: they recently announced.  MTD1 and MTD2 will not produce identical results to Guppy move table as they have been designed targeting a different application, however, there are some parameters that we can tune to get comparable results to Guppy - I beleive.




Regards

**Comment by loganylchen** [comment]
Hi @hasindu2008 ,

Thanks for summarising our Twitter discussion here. I will follow your recommendations and see if they work well in my scenario. 

Best
