### ISSUE TITLE
Conda py-3.11 package

### ISSUE THREAD

**Issue by JannesSP** [hasindu2008/slow5lib#83]
Dear @hasindu2008,

can you build a conda package for python version 3.11 for pyslow5?

Kind Regards,
Jannes

**Comment by hasindu2008** [comment]
Hi @JannesSP 

Conda version of pyslow5 is done via the bioconda channel. So this lack of Python 3.11 for pyslow5 is because bioconda is yet not doing Python 3.11 builds. Hopefully, bioconda will do this in the near future -  see https://github.com/bioconda/bioconda-recipes/issues/37805 and https://github.com/bioconda/bioconda-utils/pull/938. 

Till then, can the pyslow5 PyPI package be used - it has Python 3.11 already.

**Comment by Psy-Fer** [comment]
Hello,

Till then, just activate your conda env as be then run the pip install commands with 

`python3 -m pip install <package>` 

This will ensure it uses the conda installed python pip that you set.

Let me know if you have any troubles.

James

**Comment by hasindu2008** [comment]
@JannesSP 

Seems like bioconda now builds for Python 3.11 and the builds for pyslow5 is available https://anaconda.org/bioconda/pyslow5/files
e.g.,: [linux-64/pyslow5-1.1.0-py311h591056c_1.tar.bz2](https://anaconda.org/bioconda/pyslow5/1.1.0/download/linux-64/pyslow5-1.1.0-py311h591056c_1.tar.bz2)

Could you try if it works for you?

**Comment by hasindu2008** [comment]
Closing the issue for now. Feel free to reopen if there are any more issues.
